name: My First CI/CD

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
        - name: Download Code
          uses: actions/checkout@v4

        - name: ğŸ‘‹ Hello World DevOps!
          run: |
            echo "Hello DevOps with Roxs! ğŸš€"
            date
            uname -a

        - name: ğŸ§ª Math Test
          run: |
            if [ $((2+2)) -eq 4 ]; then
                echo "âœ… All good"
            else
                echo "âŒ Something went wrong"
                exit 1
            fi